### ISSUE TITLE
MicroPython examples for NodeMCU

### ISSUE THREAD

**Issue by marcob1281** [metriful/sensor#12]
hi guys,
I would suggest to publish examples for NodeMCU in MicroPython.
It is very efficient for such MCU board and it is easy to integrate with IoT services.

**Comment by metriful** [comment]
Hi,

This is a good idea but we have already extensively used C/C++/Arduino and prefer not to duplicate things.

If you want to make your own MicroPython version, you could start from the Raspberry Pi examples which use normal Python (very similar).
