### ISSUE TITLE
Shinyei PPD42 - ppL unit of measure

### ISSUE THREAD

**Issue by MynameisComo** [metriful/sensor#19]
Hi,
I would like to understand which kind of output value is shown by your code, what means ppL unit of measure? As per producer docs they refer to pcs/0.01cf unit of measure, and the sample value is get out every 30 seconds (if I understud well).
Could you please explain ppL unit of measure and core logic regarding this acquiring?
Thanks in advance.
Marco

**Comment by metriful** [comment]
Hi,

ppL means "particles per litre"

pcs/0.01cf means "particles per 0.01 cubic feet"

0.01 cf is 0.283 litre, so we converted to metric.

The 30 seconds is the manufacturer's recommended minimum signal averaging time.
