### ISSUE TITLE
espeasy

### ISSUE THREAD

**Issue by bjbaerken** [metriful/sensor#20]
has someone tested the metrifull with ESPEasy?
I have esp32-wroom-32 and I want to add this sensor to it. 

Whit the I2C scan it sees 0x71 but not with supported devices.

**Comment by metriful** [comment]
Hi,

We have not tested ESPEasy but you can use your ESP32 board without ESPEasy. Just use the Arduino IDE to load the software we provide in sensor/Arduino

**Comment by bjbaerken** [comment]
I know that is possible but that does not integrate with my existing projects. 
I will try to use the scripts you provided here on github to build a plugin for espeasy. 
I believe it should be possible.
