### ISSUE TITLE
Publishing library 

### ISSUE THREAD

**Issue by hosek** [metriful/sensor#22]
Hi, are you planing to publish library in platform managers for ArduinoIDE and Platformio?
https://platformio.org/lib/search?query=metriful&page=1
It will help a lot to make other integrations like Metriful component in ESPHome
Thanks

**Comment by metriful** [comment]
We do not currently have plans for that.

**Comment by hosek** [comment]
And would you mind if I will publish my fork as Unofficial version? Thanks

**Comment by metriful** [comment]
Yes, that is OK as it is MIT licensed. You just need to include a copy of the original LICENSE.txt file.
