### ISSUE TITLE
Temperature calibration

### ISSUE THREAD

**Issue by rmazzali** [metriful/sensor#25]
Hello,
I created a (temporary) custom carton box to hold the sensors and the Pi zero board that runs the logic. The Metriful board is outside the case, the other components are inside.
The board and PPD42 sensors generate heat and this affects the temperature reading. 
Does anyone have any suggestion to make a better case or find out a way to calibrate differently the temperature ?
thank you

**Comment by metriful** [comment]
The Pi and PPD42 generate a lot of heat, so you need to keep the Metriful board separate and insulated from them, including heat conduction through the case walls.

If there is self-heating from the Metriful board you can try:
- Change its orientation, as this can affect heat transfer
- Use longer cycle period
- Subtract a constant temperature offset in software - this is recommended by the temperature sensor manufacturer
