### ISSUE TITLE
Use with Heltec Wifi Kit 32

### ISSUE THREAD

**Issue by KenDodman** [metriful/sensor#3]
https://robotzero.one/heltec-wifi-kit-32/
This looks like a great little board for the metriful. Comes with a handy little display. It uses the same esp32 chips as the Arduino Nano 33 IoT. 

Will this work with the Heltec wifi 32?

**Comment by metriful** [comment]
This Heltec board should be hardware compatible with the Metriful MS430 (it is the correct voltage and has an I2C port). So it should work OK, as long as you can adapt/create the software yourself.

If you want to use the software examples on this repository, you will need to add a section to host_pin_definitions.h

It probably uses the Wire library for I2C, just like the Arduinos. The WiFi commands/setup may need editing but are probably similar to the ones for the NodeMCU/ESP8266.
