### ISSUE TITLE
Small issue in README.md in the table 'Wiring for ESP8266'

### ISSUE THREAD

**Issue by yvesLudwig** [metriful/sensor#33]
Dear Metriful,

In the CHANGELOG.md, it is indicated that, for version [3.2.0] of the 2023-11-19 : 
      «Swap SDA and SCL pin definitions for ESP8266 in host_pin_definitions.h to match the standard defaults.».

This is correct, but unfortunately, this change was not propagated in the README.md, in the table «Wiring for ESP8266».

If connection between ESP8266 and Metriful board is done according the current README.md,
the 'ready_assertion_event' will always remain 'false'.

Kind regards,

Yves

**Comment by metriful** [comment]
Thank you very much. This is now fixed.
