### ISSUE TITLE
web_server.py stops working after several hours

### ISSUE THREAD

**Issue by raz0rsedge1975** [metriful/sensor#35]
Hello,

after a recent apt update && apt upgrade of all my sensor pi's, mostly RPi Zero2W's the webserver stops reading sensor data after a couple of hours or days.

The python Version I am using is 3.9.2
Pip check shows all deps up to date and met
Funnily enough, the web server itself keeps running, the site is showing up with all zeros for every sensor
If I login to the pi via ssh and start any other python script located in the same folder as the web_server.py,
the output is normal and every sensor seems working...

![Garage_error2](https://github.com/metriful/sensor/assets/58987935/fd3f4f5e-b83b-404f-bcce-215cc9297f4d)

![Garage_error](https://github.com/metriful/sensor/assets/58987935/64e78487-bb76-43d6-bd98-dff95311ae79)

If I kill the process and restart web_server.py, everything is working fine for a couple of hours or days.
I am using sandisk MicroSD with enough space on it and have swap to MicroSD disabled by default on all my machines.
The RAM usage is constantly under 60MB, I am using the no desktop legacy 32bit Raspi OS.

I tried rebooting once a day but this did not solve the problem.
`pi@garage:~/sensor/Python/Raspberry_Pi $ python3 web_server.py &
[1] 2863
pi@garage:~/sensor/Python/Raspberry_Pi $ Starting the web server...
Your web page will be available at:
   http://192.168.178.66 2a02:810a:c80:29d3:a68c:8e:427d:cbec:8080
For more information on network IP addresses, run the command ifconfig in a terminal.
Press ctrl-c to exit at any time.

pi@garage:~/sensor/Python/Raspberry_Pi $ htop
pi@garage:~/sensor/Python/Raspberry_Pi $ i2cdetect -l
i2c-1   i2c             bcm2835 (i2c@7e804000)                  I2C adapter
i2c-2   i2c             bcm2835 (i2c@7e805000)                  I2C adapter
pi@garage:~/sensor/Python/Raspberry_Pi $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

If you need more Info, let me know.

**Comment by metriful** [comment]
Hi,
Thanks for this report. Please send an email to support@metriful.com and we will respond by email.
