### ISSUE TITLE
incorrect sensor reading 

### ISSUE THREAD

**Issue by daquino94** [metriful/sensor#36]
Hi, 

I just received the board and installed it via esphome on an esp32, where it is currently only running the script taken from the documentation. subsequently i have interfaced it to home assitant and vendo which are communicating properly. Every once in a while however there seems to be a drop or 'buffer'of data that does not allow some of it to be transmitted. 

Another abnormality I have found, is the incorrect reading of the pressure sensor, as it is always around 996, but the actual pressure at the moment would be 1010~ 

at the moment i see that it occurs on almost all sensors except for the light sensors. 

attached please find a reference sample 
could you please help me? 

[history.csv](https://github.com/user-attachments/files/16531199/history.csv)

**Comment by metriful** [comment]
Hi,

By "drop/buffer" do you mean the 0 values? 

1. Please send us some more information:

- Does the sensor work OK without ESPhome? Run the cycle_readout.ino example and check there are no 0s.
- Have you changed the wiring or code, compared to the sensor repository?
- What is your ESPHome version? Use command: esphome version
- What is your Home Assistant version? In HA, go to "Settings > About" and copy the text like: "Home Assistant 2023.10.3 Supervisor 2023.12.0 Operating System 10.5 Frontend 20231005.0 - latest" 
- Are any other devices attached to the ESP32? e.g. other sensors, peripherals.
- View the ESPhome logs to see if anything is reported when the 0s happen.
- Is your WiFi connection strong or are there connection problems?

Please send your response to support@metriful.com

2. The pressure sensor is generally very accurate - how did you get the 1010 value?

Note that 1010 vs 996 can be explained by an altitude difference of about 120m. If you have the other sensor alongside, it would need to be a professional-grade instrument to know if there is a problem!

If you raise/lower the sensor by about 3 metres, and wait for stabilisation, you should see a detectable change of about 30Pa. Bigger altitude changes will be more obvious.

Thanks!

**Comment by metriful** [comment]
Resolved.
